[profile.default]
src = "contracts"
out = "artifacts-foundry"
cache_path = 'cache-foundry'
libs = ["lib"]
cache = true
evm_version = 'cancun'
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
test = "test"

[profile.default.fuzz]
runs = 100

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }